import { NextSeo } from "next-seo";
import { Hero } from "../components/Hero";
import { NavBar } from "../components/NavBar";

export default function Home() {
  return (
    <div>
      <NextSeo
        title="Create Next App"
        description="Generated by create next app"
      />

      <main>
        <Hero />
      </main>

      <footer></footer>
    </div>
  );
}
