import { NextSeo } from "next-seo";

export default function Home() {
  return (
    <div>
      <NextSeo
        title="Create Next App"
        description="Generated by create next app"
      />

      <main>
        <h1 className="">hi</h1>
      </main>

      <footer></footer>
    </div>
  );
}
